server:
  port: 80
cors: #permitir acesso a esses enderecos
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000
file:
  upload-dir: /Users/antma/Downloads/UploadDIR
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/rest_spring?useTimezone=true&serverTimezone=UTC
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  servlet: #configuracao de upload e download
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc: #configuracao do swagger
  pathsToMatch:
   - /auth/**
   - /api/**/v1/** #link do controller
  swagger-ui:
    use-root-path: true