CREATE TABLE person (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  address VARCHAR(100) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);